---
# tasks file for ansible-role-cvsync

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create cvsync.conf
  template:
    src: cvsync.conf.j2
    dest: "{{ cvsync_conf_file }}"
    backup: yes
    # validate: echo %s

- name: Create cvsync_prefix
  file:
    path: "{{ item['base-prefix'] }}"
    state: directory
    owner: "{{ cvsync_user }}"
    group: "{{ cvsync_group }}"
  with_items: "{{ cvsync_config }}"
